languageCode = 'en-us'
title = 'Ana Ezquerro'
author = "anaezquerro"

[params]
    logoText = ""
    isBlogFocused = false
    showHeroImage = true
    showResumeButton = false
    name = "Ana Ezquerro"
    slogan = ""
    [[params.socials]]
        name = "GitHub"
        url = "https://github.com/anaezquerro"
    [[params.socials]]
        name = "Linkedin"
        url = "https://www.linkedin.com/in/anaezquerro01"
    [[params.socials]]
        name = "Twitter"
        url = "https://twitter.com/anaezquerro_"
    [[params.socials]]
        name = "Email"
        url = "mailto:ana.ezquerro@udc.es"
    [[params.socials]]
        name = "CV"
        url = "https://anaezquerro.github.io/certificates/resume.pdf"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "About"
    pre = "about"
    url = "/about/"
    weight = 15
  [[menu.main]]
    name = "Research"
    pre = "research"
    url = "/research/"
    weight = 30


