languageCode = 'en-us'
title = 'Ana Ezquerro'
author = "anaezquerro"

[params]
    logoText = ""
    isBlogFocused = false
    showHeroImage = true
    showResumeButton = false
    name = "Ana Ezquerro"
    slogan = ""
    [[params.socials]]
        name = "GitHub"
        url = "https://github.com/anaezquerro"
    [[params.socials]]
        name = "Linkedin"
        url = "https://www.linkedin.com/in/anaezquerro01"
    [[params.socials]]
        name = "Twitter"
        url = "https://twitter.com/anaezquerro_"
    [[params.socials]]
        name = "Email"
        url = "mailto:ana.ezquerro@udc.es"
    [[params.socials]]
        name = "CV"
        url = "https://anaezquerro.github.io/certificates/resume.pdf"

[menu]
  [[menu.main]]
    name = ""
    pre = ""
    url = "/"
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/anaezquerro"
    weight = 2
  [[menu.main]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/anaezquerro01"
    weight = 3
  [[menu.main]]
    name = "Email"
    url = "mailto:ana.ezquerro@udc.es"
    weight = 4
  [[menu.main]]
    name = "CV"
    url = "https://anaezquerro.github.io/certificates/resume.pdf"
    weight = 5



